name: Security hardening (Terraform)

on:
  pull_request:

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: aquasecurity/trivy-action@2b6a709cf9c4025c5438138008beaddbb02086f0 # 0.14.0
        with:
          scan-type: config
          scan-ref: .
          exit-code: 1
          severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
